### ISSUE TITLE
Swagger definition

### ISSUE THREAD

**Issue by Algorithman** [shopware/shopware#957]
https://github.com/shopware/platform/blob/42c8e52ea24366f3f19da913356b3356fc9dac0a/src/Core/Framework/Api/ApiDefinition/Generator/OpenApi/OpenApiSchemaBuilder.php#L239-L260

Isn't here the definition anyOf without use? All 3 properties are required and meta isn't even defined.

**Comment by shyim** [comment]
In the last releases, we fixed many issues in the Swagger definition. Can you check it again?

**Comment by Algorithman** [comment]
The mentioned part didn't even change (in 6.4.1.0). And it still will break the Swagger Tools (try to create a c# project, it won't work, since it still has the oneOf relationshipToOne/relationshipToMany).
Why don't you just transmit always an array and people can actually work with other languages than php. Isn't this the purpose of using swagger anyway?

**Comment by shyim** [comment]
Did you tried the plain json api instead of the json api?
https://developer.shopware.com/docs/guides/integrations-api/admin-api#response-format

**Comment by Algorithman** [comment]
You missed the point i wanted to convey.

I tried (and failed) to create a c# application for article/customer management etc. So i thought i use the swagger tools to create a interface class in c# (like it should be the way to go).
Though it can't create it, since these oneOf's are not processable for any strong typed language. There is just no way to tell a variable to be either a single instance or a enumeration of instances.
I don't know who had this glorious idea to keep *any* strong typed languages out of the picture.

For what purpose do you use Swagger exactly if not for interoperability with other platforms/languages?
